apiVersion: v2
name: aws-voting-app
description: A Helm chart for the voting application on AWS EKS
type: application
version: 0.1.0
appVersion: "1.0"

keywords:
  - voting
  - app
  - kubernetes
  - aws

maintainers:
  - name: DevOps
    email: devops@example.com

dependencies: []
